# Databricks notebook source
# MAGIC %sql
# MAGIC DROP TABLE IF EXISTS framework_testes.logs;
# MAGIC
# MAGIC CREATE TABLE IF NOT EXISTS framework_testes.logs (
# MAGIC   LOG_ID BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
# MAGIC   PARAM_ID INT,
# MAGIC   QUERY STRING,
# MAGIC   RESULT STRING,
# MAGIC   TIMESTAMP TIMESTAMP
# MAGIC );
# MAGIC
# MAGIC DROP TABLE IF EXISTS framework_testes.test_parameters;
# MAGIC
# MAGIC CREATE TABLE framework_testes.test_parameters (
# MAGIC   PARAM_ID INT,
# MAGIC   TEST_ID INT,
# MAGIC   SOURCE_TABLE STRING,
# MAGIC   DEST_TABLE STRING,
# MAGIC   SOURCE_TABLE_ALIAS STRING,
# MAGIC   DEST_TABLE_ALIAS STRING,
# MAGIC   JOIN_KEY STRING,
# MAGIC   SOURCE_SELECT_FIELD STRING,
# MAGIC   DEST_SELECT_FIELD STRING,
# MAGIC   SOURCE_FILTER STRING,
# MAGIC   DEST_FILTER STRING,
# MAGIC   SOURCE_GROUPBY STRING,
# MAGIC   DEST_GROUPBY STRING
# MAGIC );
# MAGIC
# MAGIC DROP TABLE IF EXISTS framework_testes.tests;
# MAGIC
# MAGIC CREATE TABLE framework_testes.tests (
# MAGIC   TEST_ID INT,
# MAGIC   TYPE STRING,
# MAGIC   NAME STRING,
# MAGIC   DESCRIPTION STRING
# MAGIC );