# Databricks notebook source
# MAGIC %sql
# MAGIC DROP TABLE IF EXISTS framework_testes.test_out_results;
# MAGIC
# MAGIC %sql
# MAGIC CREATE TABLE IF NOT EXISTS framework_testes.test_out_results (
# MAGIC   --RESULT_ID BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
# MAGIC   RESULT_ID INT,
# MAGIC   TEST_ID INT,
# MAGIC   QUERY STRING,
# MAGIC   RESULT STRING,
# MAGIC   PARTITION_FILTER_VALUE STRING,
# MAGIC   TIMESTAMP TIMESTAMP
# MAGIC );
# MAGIC
# MAGIC %sql
# MAGIC DROP TABLE IF EXISTS framework_testes.test_out_results_details;
# MAGIC
# MAGIC CREATE TABLE IF NOT EXISTS framework_testes.test_out_results_details (
# MAGIC   --DETAILS_ID BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
# MAGIC   DETAILS_ID INT,
# MAGIC   RESULT_ID INT,
# MAGIC   KEY_FIELDS STRING,
# MAGIC   TIMESTAMP TIMESTAMP
# MAGIC );
# MAGIC %sql
# MAGIC DROP TABLE IF EXISTS framework_testes.test_config_parameters;
# MAGIC
# MAGIC CREATE TABLE IF NOT EXISTS framework_testes.test_config_parameters (
# MAGIC   TEST_ID INT,
# MAGIC   TYPE_ID INT,
# MAGIC   SUBTYPE_ID INT,
# MAGIC   SOURCE_TABLE STRING,
# MAGIC   DEST_TABLE STRING,
# MAGIC   JOIN_KEY STRING,
# MAGIC   SOURCE_SELECT_FIELD STRING,
# MAGIC   DEST_SELECT_FIELD STRING,
# MAGIC   SOURCE_FILTER STRING,
# MAGIC   DEST_FILTER STRING,
# MAGIC   SOURCE_GROUPBY STRING,
# MAGIC   DEST_GROUPBY STRING,
# MAGIC   SOURCE_FLAG_PARTITION_FILTER BOOLEAN,
# MAGIC   DEST_FLAG_PARTITION_FILTER BOOLEAN,
# MAGIC   SOURCE_PARTITION_FILTER_FIELD STRING,
# MAGIC   DEST_PARTITION_FILTER_FIELD STRING,
# MAGIC   KEY_FIELDS STRING
# MAGIC );
# MAGIC
# MAGIC DROP TABLE IF EXISTS framework_testes.test_rel_set_parameter;
# MAGIC
# MAGIC CREATE TABLE IF NOT EXISTS framework_testes.test_rel_set_parameter (
# MAGIC   SET_ID INT,
# MAGIC   TEST_ID INT
# MAGIC );
# MAGIC
# MAGIC DROP TABLE IF EXISTS framework_testes.test_config_set;
# MAGIC
# MAGIC CREATE TABLE IF NOT EXISTS framework_testes.test_config_set (
# MAGIC   SET_ID INT,
# MAGIC   NAME STRING,
# MAGIC   DESCRIPTION STRING
# MAGIC );
# MAGIC %sql
# MAGIC DROP TABLE IF EXISTS framework_testes.test_config_subtype;
# MAGIC
# MAGIC CREATE TABLE IF NOT EXISTS framework_testes.test_config_subtype (
# MAGIC   SUBTYPE_ID INT,
# MAGIC   NAME STRING,
# MAGIC   DESCRIPTION STRING
# MAGIC );
# MAGIC %sql
# MAGIC DROP TABLE IF EXISTS framework_testes.test_config_type;
# MAGIC
# MAGIC CREATE TABLE IF NOT EXISTS framework_testes.test_config_type (
# MAGIC   TYPE_ID INT,
# MAGIC   NAME STRING,
# MAGIC   DESCRIPTION STRING
# MAGIC );
# MAGIC
# MAGIC %sql
# MAGIC DROP TABLE IF EXISTS framework_testes.test_rel_type_subtype;
# MAGIC
# MAGIC CREATE TABLE IF NOT EXISTS framework_testes.test_rel_type_subtype (
# MAGIC   TYPE_ID INT,
# MAGIC   SUBTYPE_ID INT,
# MAGIC   NAME STRING,
# MAGIC   DESCRIPTION STRING
# MAGIC );
# MAGIC
# MAGIC
# MAGIC
# MAGIC DROP TABLE IF EXISTS framework_testes.tests;
# MAGIC DROP TABLE IF EXISTS framework_testes.test_rel_set_parameter;